### ISSUE TITLE
Option to not error on unsafe packages which are not installed

### ISSUE THREAD

**Issue by LVerneyPEReN** [ubersan/pylic#101]
Hi,

We are using pylic internally by populating / crowdsourcing a list of known unsafe packages that we are OK with. Therefore, we end up with a default list of unsafe packages which might not be installed. In this case, pylic outputs a warning (expected) but fails with a non-zero error code.

The latter behaviour is unexpected to me, I would not expect the pylic configuration to be strictly 1 to 1 with the installed dependencies, but rather the installed dependencies to be a subset of the pylic configuration.

Would it make sense for you to add an option for not failing when an unsafe package is not installed?

Thanks

**Comment by ubersan** [comment]
Hi @LVerneyPEReN 

Thanks a lot for your request. Quite a while back there was a [similar request](https://github.com/ubersan/pylic/issues/52), but to list uninstalled `safe_licenses`.

Back then I thought that the value of protecting the user of losing sight over the actually installed licenses and unlicensed packages outweighs the hacks that have to be done to make this work on CI in situations that are described in these issues.

I definitely appreciate much more the benefit of having a centrally managed and curated list of licenses and/or unsafe packages which are then published and ingested into the internal ecosystem. How often do you update this? Do you fetch this on every CI run or do you update this manually and then check it in again? I'd be curious to hear how this populating and crowd sourcing works :slightly_smiling_face: 

I guess to still have the CI run you have to do something like `pylic check || true`? And this obviously (potentially) hurting much more than listing a few unsafe packages that are not installed.

To improve the situation for the users with these central configurations the solution you're proposing would surely work. I could see e.g. two `check` command options
- `--allow-extra-unused-packages | -p`
- `--allow-extra-safe-licenses | -l`

They could also be unified in a single option like `--non-strict`, but this is much less explicit and understandable, so I'm not sure if I like that.

These options would only affect the return code, not the printed output, so you'd still get the warning.

It then probably also makes sense to update the default `list` behavior to additionally also list these extra but uninstalled packages and licenses in extra sections. This way it would still be very easy to understand which licenses are installed and which ones are given extra. The `list` command currently does not list any dependencies - installed or not - so this would also probably be good improvement. This way users could use `list` to understand the whole situation.

`pylic` could even provide a new command (`reset`?) that would reset the configuration to the currently installed packages and licenses. It could also be used when setting up `pylic`, but then probably `init` makes more sense ... but I'm digressing :smile: 

How does this sound to you? :slightly_smiling_face:

**Comment by ubersan** [comment]
I see, thanks for explaining your process. I agree that no one cares about warnings on the CI as long as it passes, so hard failure is required to get attention.

Let me allocate some time in the next few evenings and work on this. `pylic` doesn't yet have the concept of command options, so it will be a bit more work, but surely worthwhile :slightly_smiling_face: Let me give an update soon about the progress of this ... Of course any kind of contribution is more than welcome! :slightly_smiling_face:

**Comment by ubersan** [comment]
hey @LVerneyPEReN This was released in version `3.2.0` :slightly_smiling_face: It would be awesome if you could give it a shot and then feedback if all is working according to plan :slightly_smiling_face:

**Comment by LVerneyPEReN** [comment]
Hi @ubersan,

Sorry for my late feedback on this one, and thanks a lot for the very quick fix! The new behavior is perfect for our use case, many thanks!

**Comment by ubersan** [comment]
awesole, glad to hear it works as expected😊👍
